### ISSUE TITLE
Pipe broken

### ISSUE THREAD

**Issue by Stock84-dev** [cirala/vifmimg#1]
When I preview images vifm freezes and image isn't displayed.
When run from terminal it outputs this:
`
/usr/bin/vifmrun: line 14: 16287 Broken pipe             tail --follow "$FIFO_UEBERZUG"
     16288 Illegal instruction     (core dumped) | ueberzug layer --silent --parser bash 2>&1 > /dev/null
` 
I have copied vifmrun and vifmimg to /usr/bin/ which is already in $PATH and run
`chmod +x /usr/bin/vifmimg`
`chmod +x /usr/bin/vifmrun`
Opened vifm by `vifmrun`.
Also I can see that pipe is created in ranger. 

python-ueberzug 18.1.3-2, vifm 0.10-1
Shell: bash 5.0.7
Terminal: urxvt - happens on all others that I have tested
OS: Manjaro

**Comment by thimc** [comment]
Which version of Python-Pillow are you using? I highly recommend that you get the SIMD version which is the fork for better image processing performance.

**Comment by sQVe** [comment]
I'm using `python-pillow-simd` version `1:5.3.0` and getting a similar issue. Instead of **Illegal instruction** I'm getting **Segmentation fault**.

This only happens on specific images too, usually quite large wallpaper images (jpegs)

**Comment by Stock84-dev** [comment]
Pillow-SIMD       5.3.0.post1
Now when i launch vifmrun it overwrites this on top of vifm interface. I don't think I have changed anything, but looks like an ueberzug issue.
`
File "/usr/bin/ueberzug", line 11, in <module>
load_entry_point('ueberzug==18.1.3', 'console_scripts', 'ueberzug')()
File "/usr/lib/python3.7/site-packages/ueberzug/ueberzug.py", line 225, in main
main_layer(options)
File "/usr/lib/python3.7/site-packages/ueberzug/ueberzug.py", line 175, in main_layer
window_infos = xutil.get_parent_window_infos()
File "/usr/lib/python3.7/site-packages/ueberzug/xutil.py", line 159, in get_parent_window_infos
pid_window_id_map = get_pid_window_id_map()                                                                                    
File "/usr/lib/python3.7/site-packages/ueberzug/xutil.py", line 98, in get_pid_window_id_map
Xlib.X.AnyPropertyType)
AttributeError: 'NoneType' object has no attribute 'value'
`

**Comment by thimc** [comment]
Closed as this issue is related to ueberzug itself and not vifmimg.
