### ISSUE TITLE
Vifm freezing when looking at an image that should have a preview

### ISSUE THREAD

**Issue by Dinglesworth** [cirala/vifmimg#18]
Whenever I use vifm with this script the preview image does not appear for any file type and causes the entire program to crash and just locks up the terminal. I have all of the dependencies installed for both Ueberzug and this script.

**Comment by TornaxO7** [comment]
is there an error message and where do you run `vifm`?

**Comment by zoj613** [comment]
Same thing happens with me. It happens randomly too but very often.
