### ISSUE TITLE
Clearing preview for menus or dropping to shell

### ISSUE THREAD

**Issue by J-Reis** [cirala/vifmimg#19]
This script is great and I really appreciate your sharing it. Would have taken me weeks or months to cludge my way through getting something like this working (might have been beyond my abilities entirely, in fact). So thanks again, cheers!

Only hitch left on my path to vifm nirvana is that active previews cover vifm's menus (for example the sort menu 'S') such that I need to move off any previewable filetype in order to be able to see the menu properly. Corollary to this, the preview also sticks around if I drop to shell (with 's') covering some portion of the terminal. There doesn't seem to be any way to clear this. I understand this is just how ueberzug (or hacking image view into term at all) works, that it just covers the area specified and you don't get any kind of z-level control … but it would be great if I could maybe map a hotkey or something to blank/clear the preview manually? Hate to bother you with my ignorance, but I'm simply not savvy enough to know where to start with something like that and it might be a feature someone else would appreciate also.

**Comment by TornaxO7** [comment]
I know what you mean. I couldn't find a solution for the menu problem as well, but I found a solution for jumping into the Shell!
First of all, add a new command:
```vim
command! clear vifmimg clear
```
After that, just remap your key:
```vim
nmap S :clear | shell<Cr>
```
This will close the preview image before entering the Shell.

Somehow the developers aren't responding anymore.

**Comment by J-Reis** [comment]
Ah, this is good! I've been able to improve most of my little vexations thanks to your advice.

- Drop to shell works as you've described, brilliant!
- I remapped the menus that I use most often to include the clear command.
`nnoremap S :clear | sort<cr>`
`nnoremap r :clear | file<cr>`
`nnoremap m :clear | marks<cr>`
`nnoremap U :clear | undolist<cr>`
- the rest can be handled tolerably well by using w to toggle off the preview pane before opening the menu

All that's left is that informational dialogues and confirmations are still covered. There may be a way to sort that too, but I'm at the end of my meager skill for now.

Thanks for pointing me in a good direction, I'm pleased to have made a bit of progress!

J

P.S. I've got no expectations of the dev, they developed the script and were kind enough to leave it here for posterity, which is a lot more than I've done, lol. If I was a better man (and a lot more competent) I could submit a patch to the vifm project to get this all working out of the box. May happen someday.

**Comment by TornaxO7** [comment]
> Ah, this is good! I've been able to improve most of my little vexations thanks to your advice.

This is good to hear :)

You could try my fork to get (hopefully) a better performance: https://github.com/cirala/vifmimg/pull/17

**Comment by J-Reis** [comment]
This is the wrong place for this I imagine. But how feasible would it be to have the script check the filesize at the start and just exit if it is over, say, 3 MB? I've got both images and (a lot) of pdfs that are dozens or even hundreds of MB and the script hangs noticeably on them, obviously.

**Comment by TornaxO7** [comment]
I've got an idea. I could try to let the script cache *all* pdf files at once when you're entering a directory. So you it'll just lag one time. But I don't know how to achieve that.

**Comment by thimc** [comment]
Cached previews are now implemented in the commit 3372889d5bfd65cb590e2e3411813ec98676a392

I'm not able to reproduce this error in the latest version, please pull the latest version and retry.

**Comment by J-Reis** [comment]
My machine is on Debian Stable, so I'm a version back with Vifm 0.10 that said the current version of the script behaves much the same way for me as the older one, with the image review persisting over menus and in shell.

note: I did need to create the ~/.cache/vifm directory to get image previews working with the new script. As well as edit the pdf entry in vifmrc to read 'vifmimg pdf' instead of 'vifm pdfpreview'. Otherwise everything is the same.

Obviously I'm a poor test case as this may well be due to my outdated version of vifm or some other change I've made and forgotten about in vifmrc.

**Comment by thimc** [comment]
Thank you for your feedback. The mkdir issue should now be solved in the latest commit.

Yes, I've changed the whole case system in the vifmimg script so all preview lines needs to be changed. Check the readme for more info.

But your issue still persists then I assume? When you drop back to terminal the last preview is still there? 
The reason I'm asking is that I use alacritty and I haven't been able to reproduce this error.

**Comment by J-Reis** [comment]
Apologies for the slow reply. Yes the issues described with the image remaining on menu load or drop to shell are still present, even using the new version from git (as of March 13). I'm just using stock xterm, only customization is basic color & font stuff via .Xresources

The workaround of `nnoremap s :clear | shell<cr>` & `nnoremap S :clear | sort<cr>` etc. for various things works fine (though as far as I know I can't change information/error messages). I removed the remap for drop-to-shell to produce the examples linked below.

https://postimg.cc/gallery/8vCsyDR

**Comment by sdsaati** [comment]
Thank you guys, I did this with your helps:
```vim
command! clear vifmimg clear
nnoremap j :clear<cr>j
nnoremap k :clear<cr>k
```

**Comment by TornaxO7** [comment]
Hmm... that's strange, normally you don't need to add the clear command for j and k.

**Comment by sdsaati** [comment]
@TornaxO7 that's true and that's why I changed that later to J and K (shift+j and shift+k), in this case it's more easier to me whenever I wanted to clear things out, just press a shift too

**Comment by TornaxO7** [comment]
But doesn't the image get cleared automatically if you press j and k?

**Comment by sdsaati** [comment]
not in my case

**Comment by TornaxO7** [comment]
what's in your `filetypes.vifm` file?

**Comment by sdsaati** [comment]
I don't have that file

**Comment by sdsaati** [comment]
btw, I use your clear command, because whenever I user `w` for preview an image or a video, most of the time, it will persist and for getting rid of that, I used your clear command, with J and K keys.

**Comment by TornaxO7** [comment]
Wait, hold on, then how are you getting the preview images?

**Comment by TornaxO7** [comment]
I mean, do you have something like this?
```vim
fileviewer <image/*>
        \ vifmimg draw %px %py %pw %ph %c
        \ %pc
        \ vifmimg clear
```

**Comment by sdsaati** [comment]
Oh, yes I have those, and I have the last line too, but it wont work as expected

**Comment by TornaxO7** [comment]
that's strange
