### ISSUE TITLE
Non-blocking image load

### ISSUE THREAD

**Issue by AckslD** [cirala/vifmimg#20]
When going over multiple images which takes some time to load I loose control over vifm until the all images are loaded. For example if each image would take one second to load and I press `j` 10 times in a directory with images I have to wait 10 seconds before I gain control again. This does not happen in for example [`fzfimg`](https://github.com/seebye/ueberzug/blob/master/examples/fzfimg.sh). Any idea how one could handle the loading of images without blocking input to `vifm`?

**Comment by PRESFIL** [comment]
It is not `vifmimg` problem. `vifm` does not using separate threads for previewing. See this [thread](https://github.com/vifm/vifm/issues/481).

Some work is done and you can compare the stable version and -git version (`vifm-git` for Arch-base distributions). But the work is still underway.

**Comment by AckslD** [comment]
I see, thanks a lot for the information @PRESFIL! :)
