### ISSUE TITLE
/usr/bin/vifmimg: line 56 :: No such file or directory

### ISSUE THREAD

**Issue by Myusuki** [cirala/vifmimg#22]
When I try to image preview in vifm it says that the file or directory doesn't exist. I have put both vifmimg and vifmrun in /usr/bin and made them executable through sudo chmod 777. Any way to fix this?  Also I'm using Manjaro if that helps.

**Comment by jose1711** [comment]
Same problem on Arch (but since Manjaro is based on Arch it's not really surprising).

Edit (2nd):
Are you sure you're using `vifmrun` to execute `vifm`? The problem disappears for me (this is needed for FIFO creation)

**Comment by Myusuki** [comment]
> Same problem on Arch (but since Manjaro is based on Arch it's not really surprising).
> 
> Edit (2nd):
> Are you sure you're using `vifmrun` to execute `vifm`? The problem disappears for me (this is needed for FIFO creation)

What do you mean exactly by using vifmrun to execute vifm? I don't really understand how you're supposed to do that.

**Comment by jose1711** [comment]
Instead of typing `vifm` into terminal window type `vifmrun`.

**Comment by Myusuki** [comment]
> Instead of typing `vifm` into terminal window type `vifmrun`.

ok I'll try it rn and see if it'll work. thx a lot.

**Comment by Myusuki** [comment]
And it works now! thx for the help @jose1711!! rlly appreciate it!
