### ISSUE TITLE
POSIX

### ISSUE THREAD

**Issue by explosion-mental** [cirala/vifmimg#26]
Hi, I just had the time to make this POSIX compliant, which is always good. The difference is that the parser is not bash but a json file filled with printf s.
Also added a docx ,pptx, (and prob etc) viewer by converting them into pdf.

https://github.com/explosion-mental/scripts/blob/main/vifmimg
https://github.com/explosion-mental/scripts/blob/main/vifmrun

sorry too noob to pr.

**Comment by cirala** [comment]
POSIX compli
