### ISSUE TITLE
`vifmrun` looks for `vifmimg` in a hardcoded path

### ISSUE THREAD

**Issue by CosmosAtlas** [cirala/vifmimg#27]
https://github.com/cirala/vifmimg/blob/e942606d01d2951eecc2e975bc3163161b2c651b/vifmrun#L20

I get errors when running *vifm* via `vifmrun`, and the error seems to suggest that `vifmrun` is looking for `vifmimg` is the fixed path.

The current readme suggests vifmimg could be anywhere in path. Not sure whats the best way to fix this.

**Comment by PRESFIL** [comment]
@cirala could you replace `"$HOME/.config/vifm/scripts/vifmimg" clear` with `vifmimg clear`?

**Comment by thimc** [comment]
Not sure why this was done in the first place to be honest :) Done!
