### ISSUE TITLE
Anomaly of display of the images 

### ISSUE THREAD

**Issue by hutou** [cirala/vifmimg#34]
Hi,
I did the installation as indicated, and under Kitty, it works. 

However, I noticed a little annoying dysfunction: when browsing the images, some of them are displayed very briefly (or not at all) and are replaced by a black rectangle, and then you have to go back to the image, sometimes several times, to get the display.

This anomaly apparently occurs randomly, and not necessarily on the same files or filetypes. 

Is this problem known? Does it have a solution?

[Edit]. I just noticed it also works under gnome-terminal (I read somewhere it was not compatible with ueberzug), with the same anomaly and also another one : the image is not properly sized, nor centered in the right pane (it is placed randomly in the right pane, and its position depends on the size of the window).

Thanks

**Comment by thimc** [comment]
Issue solved? Either way it sounds more like a ueberzug problem rather than a vifmimg problem.
