### ISSUE TITLE
Image preview covers popup menu

### ISSUE THREAD

**Issue by mark2185** [cirala/vifmimg#35]
If I have `:view` enabled and try to delete an image, the popup is shown, but then the image redraws _on top of it_.

Example:
![image](https://user-images.githubusercontent.com/8365241/141672113-458b597c-9432-481c-a01c-409eeb83d776.png)

**Comment by heelsleeh** [comment]
same problem here

**Comment by PRESFIL** [comment]
I'll just leave related issue here vifm/vifm#739.

**Comment by mark2185** [comment]
That solves it, thanks!

**Comment by heelsleeh** [comment]
works fine now, thanks all.
