### ISSUE TITLE
Vifmimg as a filepicker

### ISSUE THREAD

**Issue by tcftbl** [cirala/vifmimg#38]
Vifmimg doesn't preview images when using it as filepicker for an internet browser using the command `urxvt -e vifmrun --choose-file=picked_file`. When running the command in terminal the pictures preview on the parent terminal and not on the terminal running vifm.

**Comment by PRESFIL** [comment]
You can execute Ex command after `vifm` starts:

```sh
vifmrun --choose-file=picked_file -c ':view'
```

**Comment by tcftbl** [comment]
I don't think that fixes my problem or maybe I misunderstood your reply. I'm not sure I worded the issue as well as I could have, so here are some pictures. To simplify the issue I'll drop the argument `--choose-file=` as the behaviour is present without it.

When running the `vifmrun` everything works as expected:
![1](https://user-images.githubusercontent.com/29033868/145236739-5079c578-107b-4e81-8a5c-0a6edfa33fc6.png)

However when launching `urxvt -e vifmrun` (from the left terminal window) the preview pops up in the wrong terminal window: 
![2](https://user-images.githubusercontent.com/29033868/145237468-085ceac6-b75f-483b-afbe-da1a90b4b7bb.png)

When using a graphical browser the preview doesn't appear at all as there is no parent terminal open.

**Comment by PRESFIL** [comment]
Everything works for me correctly, the preview appears in the child
window, even if I run `urxvt -e vifmrun` from another `urxvt`.

Perhaps you have an old version of `vifmimg` or `ueberzug`?

**Comment by tcftbl** [comment]
As I checked the versions I realized I was using `tmux` in the terminal. I checked the issue with `urxvt` without `tmux` and `vifmimg` works correctly in the child window. I used the latest version of `vifmimg` and `ueberzug 18.1.9-2` from the arch linux repos.

However the problem for my usecase persists. As with tmux the previews aren't shown when using a browser (in my case `qutebrowser`). Using the browser the preview area displays the error (I should have mentioned this in my initial post):
```
/usr/bin/vifmimg: line 9: No such file or directory
```
This error refers to the line:
```
printf '{"action": "add", "identifier": "vifm-preview", "x": "%s", "y": "%s", "width": "%s", "height": "%s", "scaler": "contain", "path": "%s"}\n' "$2" "$3" "$4" "$5" "$6" > "$FIFO_UEBERZUG"
```
Where the arguments are (to my understanding) passed from `vifmrc`:
```
...
fileviewer *.pdf
    \ vifmimg pdf %px %py %pw %ph %c
    \ %pc
    \ vifmimg clear
...
```
So it would seem that for some reason `vifm` doesn't pass the filename to `vifmimg`. I'm not sure if this is the same issue as with tmux.

**Comment by PRESFIL** [comment]
How do you use `vifm` and `qutebrowser` together? Launches one from another?

You need to play it all and see environment variable the `FIFO_UEBERZUG` value
for `vifmrun` and others child processes (with `htop`, for example). Then `stat` the
resulting path to check it presence. Perhaps you do not have any of the intermediate
directories.

**Comment by tcftbl** [comment]
Thank you for swift responses @PRESFIL. Yeah `qutebrowser` launches the `urxvt -e vifmrun --choose-files=picked_file` command. However fidgeting with `ueberzug`, `vifm` and `vifmimg` seems to have solved the issue, but I have no idea what did it. A bit of a letdown. Sorry. 

However the issue with `tmux` remains when running `urxvt -e vifmrun` as the pictures in the previous post show. Although interesting on it's own my original issue is now solved.
