### ISSUE TITLE
Pass arguments of vifmrun to vifm

### ISSUE THREAD

**Issue by therealmaxmoon** [cirala/vifmimg#5]
It would be very nice, if the arguments to vifmrun would be passed to vifm like this:

`vifm $@`

So it would be still possible to give vifm arguments like the current dir it should open, like:

`vifmrun ~/documents ~/other_working_dir`

It's about this line:
https://github.com/cirala/vifmimg/blob/06495080dead3223f060e73eed45885b1ce58d21/vifmrun#L14

**Comment by thimc** [comment]
As of commit de1a81256613a77c3d06dec842aa0458e2920d5a (HEAD -> master, origin/master) this feature is now implemented. Case closed :)
