### ISSUE TITLE
Add ability to cache the preview

### ISSUE THREAD

**Issue by sdushantha** [cirala/vifmimg#9]
Creating the preview might take some time for some some files and this slows down `vifm` when you are navigating through your files.
Would it be possible to create a directory in `~/.cache` where `vifmimg` could store it's previews so that when `vifmimg` is trying to show a preview of file that it has made a preview of in the past, it can simply just use the image from the `~/.cache`?

This is just a thought, let me know what you think :)

**Comment by TornaxO7** [comment]
There should be already a cache directory.

**Comment by thimc** [comment]
Please check commit 3372889d5bfd65cb590e2e3411813ec98676a392.
